name: Enforce Branch Protection

on:
  pull_request:
    branches: [ "main" ]

permissions:
  pull-requests: write
  checks: write
  statuses: write

jobs:
  enforce-branch-protection:
    name: Verify Branch Protection Rules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Required Approvals
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });

            const requiredApprovals = 2;
            const approvedReviews = reviews.data.filter(review => review.state === "APPROVED").length;

            if (approvedReviews < requiredApprovals) {
              core.setFailed(`🚨 PR requires at least ${requiredApprovals} approvals.`);
            }

      - name: Check Status Checks
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const checks = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha
            });

            const failingChecks = checks.data.check_runs.some(check => check.conclusion === "failure");
            if (failingChecks) {
              core.setFailed("🚨 PR has failing status checks and cannot be merged.");

      - name: Verify Signed Commits in pull requests
        uses: KristianGrafana/verify-signed-commits-in-pr-action@v1